# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  python-3.11:
    paths:
      - src/statatest/
    carryforward: true
  python-3.12:
    paths:
      - src/statatest/
    carryforward: true
  python-3.13:
    paths:
      - src/statatest/
    carryforward: true
  stata:
    paths:
      - src/statatest/ado/
    carryforward: true

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "**/__pycache__/**"
  - "**/.venv/**"
