---
name: Feature Request
description: Suggest a new feature for statatest
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should be implemented?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of statatest would this affect?
      options:
        - Assertions
        - Fixtures
        - Coverage
        - CLI
        - Discovery
        - Reporting
        - Documentation
        - Other
